# -*- coding: utf-8 -*-
"""Q2_AF_CS6910.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H3WFBvKSh7OZvvX1OG5rKAJqDPEJbBKm
"""

import numpy as np

"""
Activation functions
"""

class Sigmoid():

    def __init__(self):
        pass

    def value(self, x):
      return 1/(1 + np.exp(-x))

    def grad(self, x):
      return self.value(x)*(1 - self.value(x))

class tanh():

    def __init__(self):
        pass

    def value(self, x):
      return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

    def grad(self, x):
      return 1 - self.value(x)**2